package connection.interfaces;

import java.sql.ResultSet;
import java.sql.SQLException;

public interface ISqlConnection extends IConnection {
    boolean executeRead(String query) throws SQLException;
    boolean executeWrite(String query) throws SQLException;
    ResultSet executeResult(String query) throws SQLException;
    boolean executeWriteForAutoGeneratedKey(String query) throws SQLException;
    ResultSet executeResultForAutoGeneratedKey(String query) throws SQLException;
    boolean closeConnectionWithoutResultset() throws SQLException;
}
