package com.dms.customform;

import com.dms.customform.interfaces.IAnswerDAO;
import com.dms.customform.interfaces.IAnswerModel;
import com.dms.customform.interfaces.IFormModel;
import connection.interfaces.ISqlConnection;
import connection.SqlConnectionImpl;

import java.sql.ResultSet;
import java.sql.SQLException;

public class AnswerDAO implements IAnswerDAO {
    private final ISqlConnection connectionManager;

    public AnswerDAO() {
        connectionManager = new SqlConnectionImpl();
    }

    public void insertFormResponseData(IFormModel formModel, int studentId) throws SQLException {
        try {
            for (IAnswerModel answerModel : formModel.getAnswers()) {
                String insertQuery = "INSERT INTO FormResponse(studentId, questionId, answer) VALUES ('" + studentId + "', '" + answerModel.getQuestionId() + "','" + answerModel.getAnswer() + "')";
                connectionManager.executeWriteForAutoGeneratedKey(insertQuery);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            connectionManager.closeConnectionWithoutResultset();
        }
    }

    public int getStudentId(String username) throws SQLException {
        int userId = 0;
        try {
            String fetchUserId = "SELECT studentId FROM Student where username = '" + username + "'";
            connectionManager.executeRead(fetchUserId);
            ResultSet resultSet = connectionManager.executeResult(fetchUserId);
            while (resultSet.next()) {
                userId = resultSet.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            connectionManager.closeConnection();
        }
        return userId;
    }
}
